# Copyright 2018 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

require 'google/spanner/property/instance_name'
require 'google/spanner/property/string'
require 'google/spanner/property/string_array'
require 'puppet'

Puppet::Type.newtype(:gspanner_database) do
  @doc = 'A Cloud Spanner Database which is hosted on a Spanner instance.'

  autorequire(:gauth_credential) do
    credential = self[:credential]
    raise "#{ref}: required property 'credential' is missing" if credential.nil?
    [credential]
  end

  autorequire(:gspanner_instance) do
    reference = self[:instance]
    raise "#{ref} required property 'instance' is missing" if reference.nil?
    reference.autorequires
  end

  ensurable

  newparam :credential do
    desc <<-DESC
      A gauth_credential name to be used to authenticate with Google Cloud
      Platform.
    DESC
  end

  newparam(:project) do
    desc 'A Google Cloud Platform project to manage.'
  end

  newparam(:name, namevar: true) do
    # TODO(nelsona): Make this description to match the key of the object.
    desc 'The name of the Database.'
  end

  newparam(:instance, parent: Google::Spanner::Property::InstancNameRef) do
    desc 'The instance to create the database on.'
  end

  newproperty(:name, parent: Google::Spanner::Property::String) do
    desc <<-DOC
      A unique identifier for the instance, which cannot be changed after the instance is created.
      Values are of the form projects/<project>/instances/[a-z][-a-z0-9]*[a-z0-9]. The final
      segment of the name must be between 6 and 30 characters in length.
    DOC
  end

  newproperty(:extra_statements, parent: Google::Spanner::Property::StringArray) do
    desc <<-DOC
      An optional list of DDL statements to run inside the newly created database. Statements can
      create tables, indexes, etc. These statements execute atomically with the creation of the
      database: if there is an error in any statement, the database is not created.
    DOC
  end
end
